# By default just compile and upload to the arduino
upload:
	arduino --upload --verbose --port /dev/ttyUSB0 index.ino

# Verfiy the arduino sketch will compile
verify:
	arduino --verify --verbose index.ino
